# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving_utils/protos/list_models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serving_utils/protos/list_models.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&serving_utils/protos/list_models.proto\"\x13\n\x11ListModelsRequest\"$\n\x12ListModelsResponse\x12\x0e\n\x06models\x18\x01 \x03(\t2E\n\nListModels\x12\x37\n\nListModels\x12\x12.ListModelsRequest\x1a\x13.ListModelsResponse\"\x00\x62\x06proto3')
)




_LISTMODELSREQUEST = _descriptor.Descriptor(
  name='ListModelsRequest',
  full_name='ListModelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=61,
)


_LISTMODELSRESPONSE = _descriptor.Descriptor(
  name='ListModelsResponse',
  full_name='ListModelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='ListModelsResponse.models', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['ListModelsRequest'] = _LISTMODELSREQUEST
DESCRIPTOR.message_types_by_name['ListModelsResponse'] = _LISTMODELSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListModelsRequest = _reflection.GeneratedProtocolMessageType('ListModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTMODELSREQUEST,
  '__module__' : 'serving_utils.protos.list_models_pb2'
  # @@protoc_insertion_point(class_scope:ListModelsRequest)
  })
_sym_db.RegisterMessage(ListModelsRequest)

ListModelsResponse = _reflection.GeneratedProtocolMessageType('ListModelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTMODELSRESPONSE,
  '__module__' : 'serving_utils.protos.list_models_pb2'
  # @@protoc_insertion_point(class_scope:ListModelsResponse)
  })
_sym_db.RegisterMessage(ListModelsResponse)



_LISTMODELS = _descriptor.ServiceDescriptor(
  name='ListModels',
  full_name='ListModels',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListModels',
    full_name='ListModels.ListModels',
    index=0,
    containing_service=None,
    input_type=_LISTMODELSREQUEST,
    output_type=_LISTMODELSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LISTMODELS)

DESCRIPTOR.services_by_name['ListModels'] = _LISTMODELS

# @@protoc_insertion_point(module_scope)
