# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from serving_utils.protos import list_models_pb2 as serving__utils_dot_protos_dot_list__models__pb2


class ListModelsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListModels = channel.unary_unary(
        '/ListModels/ListModels',
        request_serializer=serving__utils_dot_protos_dot_list__models__pb2.ListModelsRequest.SerializeToString,
        response_deserializer=serving__utils_dot_protos_dot_list__models__pb2.ListModelsResponse.FromString,
        )


class ListModelsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListModels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ListModelsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListModels': grpc.unary_unary_rpc_method_handler(
          servicer.ListModels,
          request_deserializer=serving__utils_dot_protos_dot_list__models__pb2.ListModelsRequest.FromString,
          response_serializer=serving__utils_dot_protos_dot_list__models__pb2.ListModelsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ListModels', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
