# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: serving_utils/protos/list_models.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import serving_utils.protos.list_models_pb2


class ListModelsBase(abc.ABC):

    @abc.abstractmethod
    async def ListModels(self, stream):
        pass

    def __mapping__(self):
        return {
            '/ListModels/ListModels': grpclib.const.Handler(
                self.ListModels,
                grpclib.const.Cardinality.UNARY_UNARY,
                serving_utils.protos.list_models_pb2.ListModelsRequest,
                serving_utils.protos.list_models_pb2.ListModelsResponse,
            ),
        }


class ListModelsStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.ListModels = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ListModels/ListModels',
            serving_utils.protos.list_models_pb2.ListModelsRequest,
            serving_utils.protos.list_models_pb2.ListModelsResponse,
        )
